apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: infra
  releaseName: loki
  values:
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1

    tableManager:
      retention_deletes_enabled: true
      retention_period: 7d

    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      podSecurityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

      compactor:
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
          enabled: false
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
      ruler:
        enable_api: false

    singleBinary:
      persistence:
        enabled: false
      extraVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: config-claim
      extraVolumeMounts:
      - mountPath: /var/loki
        name: storage
        subPath: loki

    test:
      enabled: false
    minio:
      enabled: false
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    gateway:
      enabled: false
    serviceAccount:
      create: false
    rbac:
      namespaced: true
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
