apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 30m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: infra
  releaseName: prometheus
  values:
    server:
      fullnameOverride: prometheus
      retention: "7d"
      statefulSet:
        enabled: false
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 1000
        fsGroup: 1000
      persistentVolume:
        enabled: true
        existingClaim: config-claim
        subPath: "prometheus"
      ingress:
        enabled: false
    serverFiles:
      prometheus.yml:
        rule_files: []
        scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets:
                - localhost:9090

    rbac:
      create: false
    serviceAccounts:
      server:
        create: false
    alertmanager:
      enabled: false  
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false
