apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    semver: ~20
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: infra
  releaseName: redis
  values:
    global:
      redis:
        password: ""
    networkPolicy:
      enabled: false
    architecture: "standalone"
    auth:
      enabled: false
    serviceAccount:
      create: false
      name: default
    master:
      kind: StatefulSet
      count: 1
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
      startupProbe:
        enabled: false
      livenessProbe:
        enabled: true
      readinessProbe:
        enabled: true
      persistence:
        enabled: true
        existingClaim: config-claim
        subPath: redis
      serviceAccount:
        create: false
      pdb:
        create: false
