apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts/redis
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chartRef:
        kind: OCIRepository
        name: redis
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: infra
  values:
    global:
      redis:
        password: ""
    networkPolicy:
      enabled: false
    architecture: "standalone"
    auth:
      enabled: false
    master:
      kind: StatefulSet
      count: 1
      startupProbe:
        enabled: false
      livenessProbe:
        enabled: true
      readinessProbe:
        enabled: true
      persistence:
        enabled: false
      serviceAccount:
        create: false
      pdb:
        create: false
