apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 5m
  url: https://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: redis
  targetNamespace: infra
  values:
    global:
      redis:
        password: ""
    networkPolicy:
      enabled: false
    architecture: "standalone"
    auth:
      enabled: false
    master:
      kind: StatefulSet
      count: 1
      startupProbe:
        enabled: false
      livenessProbe:
        enabled: true
      readinessProbe:
        enabled: true
      persistence:
        enabled: false
      serviceAccount:
        create: false
      pdb:
        create: false
