- hosts: all
  vars:
    ansible_ssh_user: googol
    sshd: sshd
    sshd_config: /etc/ssh/sshd_config
    sudo_config: /etc/sudoers

  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - sudo
        - curl
        - vim
        - ntp
        - net-tools
        - rsync
        - locales
        - python3
        - podman
      become: yes

    - name: set authorized key for googol
      authorized_key:
        user: googol
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Ensure en_US.UTF-8 locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present
      become: yes

    - name: disable sudo password
      lineinfile:
        path: "{{ sudo_config }}"
        line: "googol\tALL=(ALL:ALL) NOPASSWD:ALL"
      become: yes

    - name: disable remote root login
      lineinfile:
        path: "{{ sshd_config }}"
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
      register: sshd
      become: yes

    - name: disable password login
      lineinfile:
        path: "{{ sshd_config }}"
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
      register: sshd
      become: yes

    - name: limit journal log size
      lineinfile:
        path: "/etc/systemd/journald.conf"
        regexp: "^#?SystemMaxUse="
        line: "SystemMaxUse=2G"
      become: yes

    - name: limit journal log rotate time
      lineinfile:
        path: "/etc/systemd/journald.conf"
        regexp: "^#?MaxRetentionSec="
        line: "MaxRetentionSec=30day"
      become: yes

    - name: restart sshd
      service: name=sshd state=restarted
      when: sshd.changed
      become: yes
