- hosts: localhost
  connection: local

  tasks:
    - name: upgrade brew
      shell: |
        brew update
        brew upgrade
        brew cleanup

    - name: update go binaries
      shell: |
        ./go_lsp_update.sh
