- hosts: localhost
  connection: local

  tasks:
    - name: upgrade brew
      shell: |
        brew update
        brew upgrade
        brew cleanup

    - name: update go binaries
      shell: |
        go install golang.org/x/tools/gopls@latest
        go install github.com/nametake/golangci-lint-langserver@latest
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
