---
- hosts: mediaserver
  vars:

  tasks:
    - name: mount multimedia
      include_tasks: tasks/mount_mutimedia.yaml

    - name: add plex apt key
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present
      become: yes

    - name: add plex apt repository
      apt_repository:
        filename: jellyfin
        repo: "deb https://downloads.plex.tv/repo/deb public main"
        state: present
        update_cache: yes
      become: yes

    - name: plex configuration directory
      file:
        path: /etc/systemd/system/plexmediaserver.service.d
        mode: 0755
        state: directory
      become: yes

    - name: plex configurations
      copy:
        dest: /etc/systemd/system/plexmediaserver.service.d/override.conf
        mode: 0644
        content: |
          [Service]
          Environment="PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/mnt/multimedia/.config/plex"
          User=googol
          Group=googol
      become: yes

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - plexmediaserver
        - nginx
      become: yes

    - name: nginx configuration
      copy:
        dest: /etc/nginx/sites-available/default
        mode: 0644
        content: |
          server {
            listen 80;
            server_name _ default_server;

            #Forward real ip and host to Plex
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Sec-WebSocket-Extensions $http_sec_websocket_extensions;
            proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
            proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;

            #Websockets
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            #Buffering off send to the client as soon as the data is received from Plex.
            proxy_redirect off;
            proxy_buffering off;

            location / {
              proxy_set_header   X-Forwarded-For $remote_addr;
              proxy_set_header   Host $http_host;
              proxy_pass         "http://127.0.0.1:32400";
            }
          }
      become: yes

    - name: enable plex service
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
        daemon_reload: yes
      with_items:
        - plexmediaserver.service
        - nginx.service
      become: yes
