---
- hosts: mediaserver
  vars:

  tasks:
    - name: mount multimedia
      include_tasks: tasks/mount_mutimedia.yaml

    - name: add jellyfin apt key
      apt_key:
        url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
        state: present
      become: yes

    - name: add jellyfin apt repository
      apt_repository:
        filename: jellyfin
        repo: "deb [arch=amd64] https://repo.jellyfin.org/debian bullseye main"
        state: present
        update_cache: yes
      become: yes

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - jellyfin
        - nginx
      become: yes

    - name: nginx configuration
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
            listen 80;
            server_name _ default_server;

            location / {
              proxy_set_header   X-Forwarded-For $remote_addr;
              proxy_set_header   Host $http_host;
              proxy_pass         "http://127.0.0.1:8096";
            }
          }
      become: yes

    - name: enable qbittorrent service
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
        daemon_reload: yes
      with_items:
        - jellyfin.service
        - nginx.service
      become: yes
