---
apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  name: "iot"
spec:
  selector:
    matchLabels:
      app: iot
  podMetricsEndpoints:
  - port: "http"
    path: "/api/prometheus"
    interval: "30s"
    metricRelabelings:
    - sourceLabels: ["__name__"]
      regex: 'hass_.*'
      action: "keep"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot
  labels:
    app: iot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: iot
        image: ghcr.io/home-assistant/home-assistant:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8123
          name: "http"
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/ttyACM0
          name: dev-dongle
        - mountPath: /config
          name: config
        securityContext:
          privileged: true
        env:
        - name: "TZ"
          value: "Europe/Berlin"
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 512Mi
      # hostNetwork: true
      volumes:
      - name: dev-dongle
        hostPath:
          path: /dev/ttyACM0
      - name: config
        hostPath:
          path: /mnt/data/config/ha
---
apiVersion: v1
kind: Service
metadata:
  name: iot
spec:
  type: ClusterIP
  selector:
    app: iot
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot
spec:
  rules:
  - host: "iot.zhaohai.li"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iot
            port:
              number: 8123
