apiVersion: apps/v1
kind: Deployment
metadata:
  name: metatube
  labels:
    app: metatube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metatube
  template:
    metadata:
      labels:
        app: metatube
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: metatube
        image: ghcr.io/metatube-community/metatube-server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: metatube
spec:
  type: ClusterIP
  selector:
    app: metatube
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: metatube
spec:
  parentRefs:
  - name: entrypoints
    namespace: infra
    sectionName: lan-https
  hostnames:
  - "metatube-p.zhaohai.li"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: metatube
      port: 8080
