version: '3'
services:

  server:
    image: "rancher/k3s:v1.24.1-k3s1"
    container_name: k3s-server
    # command: server
    command:
    - server
    - "--https-listen-port"
    - '6443'
    - "--tls-san"
    - 192.168.170.138
    - "--kube-apiserver-arg"
    - service-node-port-range=30000-32767
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    # restart: always
    environment:
    - K3S_KUBECONFIG_OUTPUT=/var/lib/rancher/k3s/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    ports:
    - 6443:6443  # Kubernetes API Server
    - 80:80      # Ingress controller port 80
    - 443:443    # Ingress controller port 443
    volumes:
    - "/share/System/k3s/log:/var/log"
    - "/share/System/k3s/lib/kubelet:/var/lib/kubelet"
    - "/share/System/k3s/etc/rancher:/etc/rancher"
    - "/share/System/k3s/lib/cni:/var/lib/cni"
    - "/share/System/k3s/lib/rancher/k3s:/var/lib/rancher/k3s"
