#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $local_fs $network $named $portmap $remote_fs $syslog $time
# Required-Stop:     $local_fs $network $named $portmap $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# create links: update-rc.d -f ss-server defaults
# remove links: update-rc.d -f ss-server remove

user="user:group"
cmd=""
name=`basename $0`

pid_file="/var/run/www/${name}.pid"
stdout_log="/var/log/${name}.log"
stderr_log="/var/log/${name}.err"

daemon_ctl="daemon -n ${name} -F ${pid_file}"

is_running() {
	${daemon_ctl} --running
}

case "$1" in
	start)
	if is_running; then
		echo "Already started"
	else
		echo "Starting $name"
		sudo ${daemon_ctl} -X "${cmd}" -r -U -O ${stdout_log} -E ${stderr_log} -u ${user}
		if ! is_running; then
			echo "Unable to start, see $stdout_log and $stderr_log"
			exit 1
		fi
	fi
	;;
	stop)
	if is_running; then
		echo "Stopping $name"
		${daemon_ctl} --stop
	else
		echo "Not running"
	fi
	;;
	restart)
	if is_running; then
		echo "Restart $name"
		${daemon_ctl} --restart
	else
		$0 start
	fi
	;;
	status)
	if is_running; then
		echo "Running"
	else
		echo "Stopped"
		exit 1
	fi
	;;
	*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac

exit 0
