version: "3"

services:
  qbittorrent:
    hostname: qbittorrent
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
    - /share/Multimedia/.config:/config:rw
    - /share/Multimedia:/mnt/Multimedia:rw
    environment:
    - TZ="Europe/Berlin"
    - PUID=500
    - PGID=100
    - WEBUI_PORT=8888
    network_mode: host
    # ports:
    # - 16881:16881
    # - 16881:16881/udp
    # - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G

  jellyfin:
    hostname: jellyfin
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 500:100
    network_mode: "host"
    # ports:
      # - 8096:8096
    volumes:
      - /share/Multimedia/.config:/config
      - /share/Multimedia/.config/cache:/cache
      - /share/Multimedia:/media
    environment:
      - JELLYFIN_PublishedServerUrl=http://nas:8096
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
