version: "3"

services:
  qbittorrent:
    hostname: qbittorrent
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
    - /share/Multimedia/.config:/config:rw
    - /share/Multimedia:/mnt/Multimedia:rw
    environment:
    - TZ="Europe/Berlin"
    - PUID=500
    - PGID=100
    - WEBUI_PORT=8888
    ports:
    - 16881:16881
    - 16881:16881/udp
    - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G

  jellyfin:
    hostname: jellyfin
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 500:100
    ports:
    - 8096:8096
    - 8920:8920
    - 1900:1900/udp
    - 7359:7359/udp
    volumes:
      - /share/Multimedia/.config:/config
      - /share/Multimedia/.config/cache:/cache
      - /share/Multimedia:/media
    environment:
      - JELLYFIN_PublishedServerUrl=http://nas:8096
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
