version: '3'

services:
  server:
    labels:
      - "traefik.http.routers.k3s.ignore"
    image: "rancher/k3s:v1.28.4-k3s2"
    container_name: k3s
    hostname: k3s
    # restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    command:
      - "server"
      - "--tls-san=nas"
      - "--tls-san=nas.local"
      # - "--service-node-port-range=1024-55535"
    tmpfs:
      - /run
      - /var/run
    environment:
      - K3S_KUBECONFIG_OUTPUT=/var/lib/rancher/k3s/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - /share/System/config/k3s:/var/lib/rancher/k3s
      - /etc/machine-id:/etc/machine-id
      - /:/hostfs
      - /share/System:/share/System
      - /share/Media:/share/Media
    ports:
      - 6443:6443
      - 7080:80
      - 7443:443
