version: "3"

networks:
  default:
    external:
      name: gateway_default

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    hostname: prometheus
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`monitor.zhaohai.li`)"
      - "traefik.http.routers.prometheus.entrypoints=https"
    user: root:root
    entrypoint: []
    command:
      - "/bin/sh"
      - "-c"
      - |
        ls -lhad /prometheus/data
        echo "$${PROMETHEUS_CONFIG}" > /etc/prometheus/prometheus.yml
        exec /bin/prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.retention.time=7d
    volumes:
      - type: bind
        source: /share/System/config/prometheus/data
        target: /prometheus/data
    expose:
      - 9090
    environment:
      PROMETHEUS_CONFIG: |
        global:
          scrape_interval: 10s
          external_labels:
            monitor: 'codelab-monitor'
        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']
          - job_name: 'traefik'
            static_configs:
              - targets: ['gateway.zhaohai.li']
          - job_name: erx
            static_configs:
              - targets: ['192.168.10.1']
            metrics_path: /snmp
            params:
              module:
                - edgerouterx
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: snmp-exporter:9116
          - job_name: nas
            static_configs:
              - targets: ['192.168.10.2']
            metrics_path: /snmp
            params:
              module:
                - qnap
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: snmp-exporter:9116

  grafana:
    image: grafana/grafana-enterprise:main
    container_name: grafana
    hostname: grafana
    user: root:root
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    labels:
      - "traefik.http.routers.grafana.rule=Host(`graph.zhaohai.li`)"
      - "traefik.http.routers.grafana.entrypoints=https"
    volumes:
      - type: bind
        source: /share/System/config/grafana/data
        target: /var/lib/grafana
    expose:
     - 3000
    environment:
     - GF_SERVER_ROOT_URL=https://graph.zhaohai.li/

  snmp-exporter:
    image: prom/snmp-exporter:v0.22.0
    container_name: snmp-exporter
    hostname: snmp-exporter
    labels:
      - "traefik.http.routers.snmp-exporter.role=``"
      - "traefik.http.routers.snmp-exporter.entrypoints=``"
    expose:
      - 9116
    entrypoint: []
    command:
      - '/bin/sh'
      - '-c'
      - |
        echo "$${SNMP_YAML}" > /snmp.yaml
        exec /bin/snmp_exporter --config.file=/snmp.yaml
    environment:
      SNMP_YAML: |
        # WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
        edgerouterx:
          walk:
          - 1.3.6.1.2.1.31.1.1.1.1
          - 1.3.6.1.2.1.31.1.1.1.10
          - 1.3.6.1.2.1.31.1.1.1.15
          - 1.3.6.1.2.1.31.1.1.1.6
          get:
          - 1.3.6.1.2.1.25.1.1.0
          - 1.3.6.1.4.1.2021.11.11.0
          - 1.3.6.1.4.1.2021.4.11.0
          - 1.3.6.1.4.1.2021.4.5.0
          metrics:
          - name: hrSystemUptime
            oid: 1.3.6.1.2.1.25.1.1
            type: gauge
            help: The amount of time since this host was last initialized - 1.3.6.1.2.1.25.1.1
          - name: ifHCOutOctets
            oid: 1.3.6.1.2.1.31.1.1.1.10
            type: counter
            help: The total number of octets transmitted out of the interface, including
              framing characters - 1.3.6.1.2.1.31.1.1.1.10
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ifHighSpeed
            oid: 1.3.6.1.2.1.31.1.1.1.15
            type: gauge
            help: An estimate of the interface's current bandwidth in units of 1,000,000
              bits per second - 1.3.6.1.2.1.31.1.1.1.15
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ifHCInOctets
            oid: 1.3.6.1.2.1.31.1.1.1.6
            type: counter
            help: The total number of octets received on the interface, including framing
              characters - 1.3.6.1.2.1.31.1.1.1.6
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ssCpuIdle
            oid: 1.3.6.1.4.1.2021.11.11
            type: gauge
            help: The percentage of processor time spent idle, calculated over the last
              minute - 1.3.6.1.4.1.2021.11.11
          - name: memTotalFree
            oid: 1.3.6.1.4.1.2021.4.11
            type: gauge
            help: The total amount of memory free or available for use on this host - 1.3.6.1.4.1.2021.4.11
          - name: memTotalReal
            oid: 1.3.6.1.4.1.2021.4.5
            type: gauge
            help: The total amount of real/physical memory installed on this host. - 1.3.6.1.4.1.2021.4.5
        qnap:
          walk:
          - 1.3.6.1.4.1.24681.1.3.11.1.3
          - 1.3.6.1.4.1.24681.1.3.15.1.3
          - 1.3.6.1.4.1.24681.1.3.17.1.4
          - 1.3.6.1.4.1.24681.1.3.17.1.5
          - 1.3.6.1.4.1.24681.1.3.9.1.3
          - 1.3.6.1.4.1.24681.1.3.9.1.4
          - 1.3.6.1.4.1.24681.1.4.1.1.1.1.4.3.1.3
          - 1.3.6.1.4.1.24681.1.4.1.1.1.1.5.2.1.5
          - 1.3.6.1.4.1.55062.1.10.34.1.7
          - 1.3.6.1.4.1.55062.1.10.9.1.3
          - 1.3.6.1.4.1.55062.1.10.9.1.5
          get:
          - 1.3.6.1.4.1.24681.1.3.1.0
          - 1.3.6.1.4.1.24681.1.3.2.0
          - 1.3.6.1.4.1.24681.1.3.3.0
          - 1.3.6.1.4.1.24681.1.3.4.0
          - 1.3.6.1.4.1.24681.1.3.5.0
          - 1.3.6.1.4.1.24681.1.3.6.0
          - 1.3.6.1.4.1.24681.1.4.1.1.1.3.2.0
          - 1.3.6.1.4.1.24681.1.4.1.1.1.3.3.0
          - 1.3.6.1.4.1.24681.1.4.1.1.1.3.4.0
          - 1.3.6.1.4.1.55062.1.12.13.0
          - 1.3.6.1.4.1.55062.1.12.15.0
          - 1.3.6.1.4.1.55062.1.12.7.0
          metrics:
          - name: systemCPU_UsageEX
            oid: 1.3.6.1.4.1.24681.1.3.1
            type: gauge
            help: system CPU usage - 1.3.6.1.4.1.24681.1.3.1
          - name: hdTemperatureEX
            oid: 1.3.6.1.4.1.24681.1.3.11.1.3
            type: gauge
            help: Hard disk temperature in centigrade. - 1.3.6.1.4.1.24681.1.3.11.1.3
            indexes:
            - labelname: hdIndex
              type: gauge
          - name: sysFanSpeedEX
            oid: 1.3.6.1.4.1.24681.1.3.15.1.3
            type: gauge
            help: System fan speed (RPM). - 1.3.6.1.4.1.24681.1.3.15.1.3
            indexes:
            - labelname: sysFanIndexEX
              type: gauge
          - name: sysVolumeTotalSizeEX
            oid: 1.3.6.1.4.1.24681.1.3.17.1.4
            type: counter
            help: System Volume total size in byte. - 1.3.6.1.4.1.24681.1.3.17.1.4
            indexes:
            - labelname: sysVolumeIndexEX
              type: gauge
          - name: sysVolumeFreeSizeEX
            oid: 1.3.6.1.4.1.24681.1.3.17.1.5
            type: counter
            help: System Volume free size in byte. - 1.3.6.1.4.1.24681.1.3.17.1.5
            indexes:
            - labelname: sysVolumeIndexEX
              type: gauge
          - name: systemTotalMemEX
            oid: 1.3.6.1.4.1.24681.1.3.2
            type: counter
            help: System total memory in byte - 1.3.6.1.4.1.24681.1.3.2
          - name: systemFreeMemEX
            oid: 1.3.6.1.4.1.24681.1.3.3
            type: counter
            help: System free memory in byte - 1.3.6.1.4.1.24681.1.3.3
          - name: systemUptimeEX
            oid: 1.3.6.1.4.1.24681.1.3.4
            type: gauge
            help: The amount of time since this host was last initialized - 1.3.6.1.4.1.24681.1.3.4
          - name: cpu_TemperatureEX
            oid: 1.3.6.1.4.1.24681.1.3.5
            type: gauge
            help: CPU temperature in centigrade - 1.3.6.1.4.1.24681.1.3.5
          - name: systemTemperatureEX
            oid: 1.3.6.1.4.1.24681.1.3.6
            type: gauge
            help: System temperature in centigrade - 1.3.6.1.4.1.24681.1.3.6
          - name: ifPacketsReceivedEX
            oid: 1.3.6.1.4.1.24681.1.3.9.1.3
            type: counter
            help: System packets received. - 1.3.6.1.4.1.24681.1.3.9.1.3
            indexes:
            - labelname: ifIndexEX
              type: gauge
          - name: ifPacketsSentEX
            oid: 1.3.6.1.4.1.24681.1.3.9.1.4
            type: counter
            help: System packets sent. - 1.3.6.1.4.1.24681.1.3.9.1.4
            indexes:
            - labelname: ifIndexEX
              type: gauge
          - name: cpuUsage
            oid: 1.3.6.1.4.1.24681.1.4.1.1.1.1.4.3.1.3
            type: gauge
            help: CPUUsage. - 1.3.6.1.4.1.24681.1.4.1.1.1.1.4.3.1.3
            indexes:
            - labelname: cpuIndex
              type: gauge
          - name: diskSmartInfo
            oid: 1.3.6.1.4.1.24681.1.4.1.1.1.1.5.2.1.5
            type: gauge
            help: DiskSmartInfo. - 1.3.6.1.4.1.24681.1.4.1.1.1.1.5.2.1.5
            indexes:
            - labelname: diskIndex
              type: gauge
            enum_values:
              -1: error
              0: good
              1: warning
              2: abnormal
          - name: availablePercent
            oid: 1.3.6.1.4.1.24681.1.4.1.1.1.3.2
            type: gauge
            help: Available percent of cache. - 1.3.6.1.4.1.24681.1.4.1.1.1.3.2
          - name: readHitRate
            oid: 1.3.6.1.4.1.24681.1.4.1.1.1.3.3
            type: gauge
            help: Read hit rate percent of cache. - 1.3.6.1.4.1.24681.1.4.1.1.1.3.3
          - name: writeHitRate
            oid: 1.3.6.1.4.1.24681.1.4.1.1.1.3.4
            type: gauge
            help: Write hit rate percent of cache. - 1.3.6.1.4.1.24681.1.4.1.1.1.3.4
          - name: enclosureSystemTemp
            oid: 1.3.6.1.4.1.55062.1.10.34.1.7
            type: gauge
            help: Enclosure System temperature in centigrade. - 1.3.6.1.4.1.55062.1.10.34.1.7
            indexes:
            - labelname: enclosureIndex
              type: gauge
          - name: volumeCapacity
            oid: 1.3.6.1.4.1.55062.1.10.9.1.3
            type: counter
            help: System Volume total size in byte. - 1.3.6.1.4.1.55062.1.10.9.1.3
            indexes:
            - labelname: volumeIndex
              type: gauge
          - name: volumeStatus
            oid: 1.3.6.1.4.1.55062.1.10.9.1.5
            type: OctetString
            help: Volume status - 1.3.6.1.4.1.55062.1.10.9.1.5
            indexes:
            - labelname: volumeIndex
              type: gauge
          - name: systemTotalMem
            oid: 1.3.6.1.4.1.55062.1.12.13
            type: counter
            help: System total memory - 1.3.6.1.4.1.55062.1.12.13
          - name: systemAvailableMem
            oid: 1.3.6.1.4.1.55062.1.12.15
            type: counter
            help: System available memory - 1.3.6.1.4.1.55062.1.12.15
          - name: firmwareUpgradeAvailable
            oid: 1.3.6.1.4.1.55062.1.12.7
            type: gauge
            help: Firmware can upgrade or not - 1.3.6.1.4.1.55062.1.12.7
