version: "3"

networks:
  default:
    name: gateway_default

services:
  gpt:
    image: ghcr.io/binary-husky/gpt_academic_nolocal:master
    container_name: gpt
    hostname: gpt
    restart: always
    labels:
      - "traefik.http.routers.gpt.rule=Host(`gpt-p.zhaohai.li`)"
      - "traefik.http.routers.gpt.entrypoints=https"
    command:
      - "/bin/bash"
      - "-c"
      - |
        export API_KEY=$$(cat /etc/openai_token)
        exec python3 -u main.py
    volumes:
      - type: bind
        source: /share/System/config/gpt_academic/uploads
        target: /gpt/private_upload
      - type: bind
        source: /share/System/config/gpt_academic/generates
        target: /gpt/gpt_log
      - type: bind
        source: /share/System/config/openai_token
        target: /etc/openai_token
    environment:
      USE_PROXY: 'False'
      LLM_MODEL: 'gpt-3.5-turbo'
      AVAIL_LLM_MODELS: '["gpt-3.5-turbo", "api2d-gpt-3.5-turbo", "gpt-4", "api2d-gpt-4", "newbing"]'
      WEB_PORT: '22303'
      ADD_WAIFU: 'False'
      DEFAULT_WORKER_NUM: '3'
    expose:
      - "22303"

  tinyfilemanager:
    image: tinyfilemanager/tinyfilemanager:2.4.7
    container_name: tinyfilemanager
    hostname: tinyfilemanager
    restart: always
    labels:
      - "traefik.http.routers.tinyfilemanager.rule=Host(`fs-p.zhaohai.li`)"
      - "traefik.http.routers.tinyfilemanager.entrypoints=https"
    command:
      - "/bin/sh"
      - "-c"
      - |
        echo "$${TINYFILEMANAGER_CONFIG}" > /var/www/html/config.php
        exec php -S 0.0.0.0:80
    volumes:
      - type: bind
        source: /share/Multimedia
        target: /share/Multimedia
    expose:
      - "80"
    environment:
      TINYFILEMANAGER_CONFIG: |
        <?php
        $$root_path = '/share/Multimedia/';
        $$use_auth = false;

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    hostname: qbittorrent
    restart: always
    labels:
      - "traefik.http.routers.qbittorrent.rule=Host(`bt-p.zhaohai.li`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    volumes:
      - type: bind
        source: /share/Multimedia
        target: /mnt/Multimedia
      - type: bind
        source: /share/System/config/qbittorrent
        target: /config
    expose:
      - "8080"
    ports:
      - 16881:16881/tcp
      - 16881:16881/udp
    environment:
      WEBUI_PORT: "8080"
      TZ: "Europe/Berlin"
      PUID: "1000"
      PGID: "100"

  jellyfin:
    image: jellyfin/jellyfin:10.8.12
    container_name: jellyfin
    hostname: jellyfin
    restart: always
    labels:
      - "traefik.http.routers.media.rule=Host(`media.zhaohai.li`)"
      - "traefik.http.routers.media.entrypoints=https"
      - "traefik.http.services.media.loadbalancer.server.port=8096"
    volumes:
      - type: bind
        source: /share/Multimedia
        target: /Multimedia
      - type: bind
        source: /share/System/config/jellyfin
        target: /config
      - type: bind
        source: /share/System/config/jellyfin/cache
        target: /cache
    expose:
      - "8096"
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
    environment:
      JELLYFIN_PublishedServerUrl: https://media.zhaohai.li

  gotosocial:
    image: superseriousbusiness/gotosocial:0.12.1
    container_name: gotosocial
    hostname: gotosocial
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:8006
    labels:
      - "traefik.http.routers.gotosocial.rule=Host(`mblog.zhaohai.li`)||Host(`gts-w.zhaohai.li`)"
      - "traefik.http.routers.gotosocial.entrypoints=https"
    environment:
      GTS_HOST: mblog.zhaohai.li
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      TZ: Europe/Berlin
    user: "0:0"
    expose:
      - "8080"
    volumes:
      - type: bind
        source: /share/System/config/gotosocial
        target: /gotosocial/storage

  nocodb:
    image: nocodb/nocodb:0.202.5
    container_name: nocodb
    hostname: nocodb
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:8006
    labels:
      - "traefik.http.routers.forms.rule=Host(`forms.zhaohai.li`)"
      - "traefik.http.routers.forms.entrypoints=https"
    volumes:
      - type: bind
        source: /share/System/config/nocodb
        target: /usr/app/data/
    expose:
      - "8080"
