version: "3"

networks:
  default:
    external:
      name: gateway_default

services:
  tinyfilemanager:
    image: tinyfilemanager/tinyfilemanager:2.4.7
    container_name: tinyfilemanager
    hostname: tinyfilemanager
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    labels:
      - "traefik.http.routers.tinyfilemanager.rule=Host(`fs.zhaohai.li`)"
      - "traefik.http.routers.tinyfilemanager.entrypoints=https"
    command:
      - "/bin/sh"
      - "-c"
      - |
        echo "$${TINYFILEMANAGER_CONFIG}" > /var/www/html/config.php
        exec php -S 0.0.0.0:80
    volumes:
      - type: bind
        source: /share/Multimedia
        target: /share/Multimedia
    expose:
      - "80"
    environment:
      TINYFILEMANAGER_CONFIG: |
        <?php
        $$root_path = '/share/Multimedia/';
        $$use_auth = false;

  qbittorrent:
    image: linuxserver/qbittorrent:4.5.4
    container_name: qbittorrent
    hostname: qbittorrent
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.http.routers.qbittorrent.rule=Host(`bt.zhaohai.li`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    volumes:
      - type: bind
        source: /share/Multimedia
        target: /mnt/Multimedia
      - type: bind
        source: /share/System/config/qbittorrent
        target: /config
    expose:
      - "8080"
    ports:
      - 16881:16881/tcp
      - 16881:16881/udp
    environment:
      WEBUI_PORT: "8080"
      TZ: "Europe/Berlin"
      PUID: "1000"
      PGID: "100"

  jellyfin:
    image: jellyfin/jellyfin:10.8.10
    container_name: jellyfin
    hostname: jellyfin
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.http.routers.media.rule=Host(`media.zhaohai.li`)"
      - "traefik.http.routers.media.entrypoints=https"
      - "traefik.http.services.media.loadbalancer.server.port=8096"
    volumes:
      - type: bind
        source: /share/Multimedia
        target: /Multimedia
      - type: bind
        source: /share/System/config/jellyfin
        target: /config
      - type: bind
        source: /share/System/config/jellyfin/cache
        target: /cache
    expose:
      - "8096"
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
    environment:
      JELLYFIN_PublishedServerUrl: https://media.zhaohai.li
