version: "3"

networks:
  default:
    name: gateway_default

volumes:
  config:

services:
  config:
    image: debian:12-slim
    container_name: config
    hostname: config
    user: "root"
    entrypoint: []
    command:
      - "/bin/sh"
      - "-c"
      - |
        echo "$${OTEL_CONFIG}" > /otel/config.yaml
    volumes:
      - config:/otel
    environment:
      OTEL_CONFIG: |
        receivers:
          otlp:
            protocols:
              grpc:
              http:

          prometheus:
            config:
              scrape_configs:
                - job_name: 'otel-collector'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['localhost:8888']
                - job_name: 'traefik'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['gateway.zhaohai.li']
                - job_name: 'erx'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['192.168.10.1']
                  metrics_path: /snmp
                  params:
                    module:
                      - edgerouterx
                  relabel_configs:
                    - source_labels: [__address__]
                      target_label: __param_target
                    - source_labels: [__param_target]
                      target_label: instance
                    - target_label: __address__
                      replacement: snmp-exporter:9116

          hostmetrics:
            # root_path: /hostfs
            scrapers:
              cpu:
              disk:
              filesystem:
              load:
              memory:
              network:
                include:
                  interfaces: [br0]
                  match_type: strict
              process:
                mute_process_exe_error: true
              processes:
              paging:

        processors:
          memory_limiter:
            check_interval: 1s
            limit_mib: 100
            spike_limit_mib: 80
          resourcedetection:
            detectors: [docker]
            timeout: 2s
            override: false
          batch:
            timeout: 5s
            send_batch_size: 100000

        exporters:
          clickhouse:
            endpoint: clickhouse://clickhouse:9000?dial_timeout=10s&compress=lz4
            username: default
            password: ""
            database: otel
            ttl_days: 3
            logs_table_name: otel_logs
            traces_table_name: otel_traces
            metrics_table_name: otel_metrics
            timeout: 5s
            retry_on_failure:
              enabled: true
              initial_interval: 5s
              max_interval: 30s
              max_elapsed_time: 300s

        service:
          # telemetry:
            # logs:
              # level: debug
          pipelines:
            traces:
              receivers: [otlp]
              processors: [resourcedetection]
              exporters: [clickhouse]
            metrics:
              receivers: [otlp, hostmetrics, prometheus]
              processors: [resourcedetection]
              exporters: [clickhouse]
            logs:
              receivers: [otlp]
              processors: [resourcedetection]
              exporters: [clickhouse]

  clickhouse:
    image: clickhouse/clickhouse-server:23.10.5
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    user: "root:root"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    volumes:
      - type: bind
        source: /share/System/config/clickhouse/data
        target: /var/lib/clickhouse/
      - type: bind
        source: /share/System/config/clickhouse/log
        target: /var/log/clickhouse-server
    expose:
      - "8123"
      - "9000"
    ports:
      - 8123:8123
      - 9000:9000
    # environment:
      # CLICKHOUSE_UID: "0"
      # CLICKHOUSE_GID: "0"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
      - SYS_NICE

  otel:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.89.0
    container_name: otel
    hostname: otel
    restart: unless-stopped
    user: "0"
    depends_on:
      config:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
    command:
      - "--config"
      - "/otel/config.yaml"
    volumes:
      - config:/otel
      - /:/hostfs
      - /proc:/proc
      - /dev:/dev
      - /usr:/usr
      - /mnt:/mnt
      - /share:/share
      - /var:/var
      - /etc:/etc
    expose:
      - "1888" # pprof extension
      - "8888" # Prometheus metrics exposed by the Collector
      - "8889" # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4317" # OTLP gRPC receiver
      - "4318" # OTLP http receiver
    ports:
      - 55679:55679 # zpages extension
    cap_add:
      - SYS_PTRACE

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    hostname: prometheus
    restart: always
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`monitor.zhaohai.li`)"
      - "traefik.http.routers.prometheus.entrypoints=https"
    user: root:root
    entrypoint: []
    command:
      - "/bin/sh"
      - "-c"
      - |
        ls -lhad /prometheus/data
        echo "$${PROMETHEUS_CONFIG}" > /etc/prometheus/prometheus.yml
        exec /bin/prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.retention.time=14d
    volumes:
      - type: bind
        source: /share/System/config/prometheus/data
        target: /prometheus/data
    expose:
      - 9090
    environment:
      PROMETHEUS_CONFIG: |
        global:
          scrape_interval: 30s
          external_labels:
            monitor: 'codelab-monitor'
        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']
          - job_name: 'traefik'
            static_configs:
              - targets: ['gateway.zhaohai.li']
          - job_name: 'nas'
            static_configs:
              - targets: ['nas-exporter:9100']
          - job_name: 'erx'
            static_configs:
              - targets: ['192.168.10.1']
            metrics_path: /snmp
            params:
              module:
                - edgerouterx
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: snmp-exporter:9116

  grafana:
    image: grafana/grafana-enterprise:10.2.0
    container_name: grafana
    hostname: grafana
    restart: always
    user: root:root
    labels:
      - "traefik.http.routers.grafana.rule=Host(`graph.zhaohai.li`)"
      - "traefik.http.routers.grafana.entrypoints=https"
    volumes:
      - type: bind
        source: /share/System/config/grafana/data
        target: /var/lib/grafana
    expose:
     - 3000
    environment:
     - GF_SERVER_ROOT_URL=https://graph.zhaohai.li/
     - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource

  nas-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: nas-exporter
    hostname: nas-exporter
    restart: always
    labels:
      - "traefik.http.routers.nas-exporter.role=``"
      - "traefik.http.routers.nas-exporter.entrypoints=``"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /host/run/udev/data:/run/udev/data:ro
      - /share/Multimedia:/rootfs:ro
    expose:
      - 9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--path.udev.data=/host/run/udev/data'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  snmp-exporter:
    image: prom/snmp-exporter:v0.22.0
    container_name: snmp-exporter
    hostname: snmp-exporter
    restart: always
    labels:
      - "traefik.http.routers.snmp-exporter.role=``"
      - "traefik.http.routers.snmp-exporter.entrypoints=``"
    expose:
      - 9116
    entrypoint: []
    command:
      - '/bin/sh'
      - '-c'
      - |
        echo "$${SNMP_YAML}" > /etc/snmp_exporter/snmp.yaml
        exec /bin/snmp_exporter --config.file=/etc/snmp_exporter/snmp.yaml
    environment:
      SNMP_YAML: |
        # WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
        edgerouterx:
          walk:
          - 1.3.6.1.2.1.31.1.1.1.1
          - 1.3.6.1.2.1.31.1.1.1.10
          - 1.3.6.1.2.1.31.1.1.1.15
          - 1.3.6.1.2.1.31.1.1.1.6
          get:
          - 1.3.6.1.2.1.25.1.1.0
          - 1.3.6.1.4.1.2021.11.11.0
          - 1.3.6.1.4.1.2021.4.11.0
          - 1.3.6.1.4.1.2021.4.5.0
          metrics:
          - name: hrSystemUptime
            oid: 1.3.6.1.2.1.25.1.1
            type: gauge
            help: The amount of time since this host was last initialized - 1.3.6.1.2.1.25.1.1
          - name: ifHCOutOctets
            oid: 1.3.6.1.2.1.31.1.1.1.10
            type: counter
            help: The total number of octets transmitted out of the interface, including framing
              characters - 1.3.6.1.2.1.31.1.1.1.10
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ifHighSpeed
            oid: 1.3.6.1.2.1.31.1.1.1.15
            type: gauge
            help: An estimate of the interface's current bandwidth in units of 1,000,000 bits
              per second - 1.3.6.1.2.1.31.1.1.1.15
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ifHCInOctets
            oid: 1.3.6.1.2.1.31.1.1.1.6
            type: counter
            help: The total number of octets received on the interface, including framing
              characters - 1.3.6.1.2.1.31.1.1.1.6
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ssCpuIdle
            oid: 1.3.6.1.4.1.2021.11.11
            type: gauge
            help: The percentage of processor time spent idle, calculated over the last minute
              - 1.3.6.1.4.1.2021.11.11
          - name: memTotalFree
            oid: 1.3.6.1.4.1.2021.4.11
            type: gauge
            help: The total amount of memory free or available for use on this host - 1.3.6.1.4.1.2021.4.11
          - name: memTotalReal
            oid: 1.3.6.1.4.1.2021.4.5
            type: gauge
            help: The total amount of real/physical memory installed on this host. - 1.3.6.1.4.1.2021.4.5
