version: "3"

networks:
  default:
    name: gateway_default

volumes:
  config:

services:
  config:
    image: debian:12-slim
    container_name: config
    hostname: config
    user: "root"
    entrypoint: []
    command:
      - "/bin/sh"
      - "-c"
      - |
        export INFLUXDB_TOKEN=$$(cat /etc/host_config/influxdb_token)
        echo "$${OTEL_CONFIG}" | sed "s/influxdb-token/$${INFLUXDB_TOKEN}/g" > /otel/config.yaml
    volumes:
      - config:/otel
      - /share/System/config/influxdb_token:/etc/host_config/influxdb_token
    environment:
      OTEL_CONFIG: |
        receivers:
          fluentforward:
            endpoint: 0.0.0.0:8006

          prometheus:
            config:
              scrape_configs:
                - job_name: 'otel-collector'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['localhost:8888']
                - job_name: 'influxdb'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['influxdb:8086']
                - job_name: 'traefik'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['gateway.zhaohai.li']
                - job_name: 'erx'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['192.168.10.1']
                  metrics_path: /snmp
                  params:
                    module:
                      - edgerouterx
                  relabel_configs:
                    - source_labels: [__address__]
                      target_label: __param_target
                    - source_labels: [__param_target]
                      target_label: instance
                    - target_label: __address__
                      replacement: snmp-exporter:9116

          hostmetrics:
            # root_path: /hostfs
            scrapers:
              cpu:
              disk:
              filesystem:
              load:
              memory:
              network:
              process:
                mute_process_exe_error: true
              processes:
              paging:

        processors:
          memory_limiter:
            check_interval: 1s
            limit_mib: 100
            spike_limit_mib: 80
          resourcedetection:
            detectors: [docker]
            timeout: 2s
            override: false
          batch:
            timeout: 5s
            send_batch_size: 100000

        exporters:
          influxdb:
            endpoint: http://influxdb:8086
            timeout: 10000ms
            org: home
            bucket: home-cluster
            token: influxdb-token
            span_dimensions:
              - service.name
              - span.name
            log_record_dimensions:
              - service.name
            metrics_schema: telegraf-prometheus-v1

            sending_queue:
              enabled: true
              num_consumers: 3
              queue_size: 10

            retry_on_failure:
              enabled: true
              initial_interval: 1s
              max_interval: 3s
              max_elapsed_time: 10s

        service:
          # telemetry:
            # logs:
              # level: debug
          pipelines:
            # traces:
              # receivers: []
              # processors: [resourcedetection]
              # exporters: [influxdb]
            metrics:
              receivers: [hostmetrics, prometheus]
              processors: [resourcedetection]
              exporters: [influxdb]
            logs:
              receivers: [fluentforward]
              processors: [resourcedetection]
              exporters: [influxdb]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    hostname: influxdb
    restart: always
    user: "root:root"
    labels:
      - 'traefik.http.routers.influx.rule=Host(`telemetry-w.zhaohai.li`) && !Path(`/ping`, `/metrics`)'
      - "traefik.http.routers.influx.entrypoints=https"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - type: bind
        source: /share/System/config/influxdb/data
        target: /var/lib/influxdb2
      - type: bind
        source: /share/System/config/influxdb/config
        target: /etc/influxdb2
    expose:
      - "8086"

  otel:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.89.0
    container_name: otel
    hostname: otel
    restart: unless-stopped
    user: "0"
    depends_on:
      config:
        condition: service_completed_successfully
      influxdb:
        condition: service_healthy
    command:
      - "--config"
      - "/otel/config.yaml"
    volumes:
      - config:/otel
      - /:/hostfs
      - /proc:/proc
      - /dev:/dev
      - /usr:/usr
      - /bin:/bin
      - /lib:/lib
      - /mnt:/mnt
      - /share:/share
      - /var:/var
      - /etc:/etc
    expose:
      - "1888" # pprof extension
      - "8888" # Prometheus metrics exposed by the Collector
      - "8889" # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4317" # OTLP gRPC receiver
      - "4318" # OTLP http receiver
    ports:
      - 8006:8006 # fluentforward
    cap_add:
      - SYS_PTRACE

  snmp-exporter:
    image: prom/snmp-exporter:v0.22.0
    container_name: snmp-exporter
    hostname: snmp-exporter
    restart: always
    labels:
      - "traefik.http.routers.snmp-exporter.role=``"
      - "traefik.http.routers.snmp-exporter.entrypoints=``"
    expose:
      - 9116
    entrypoint: []
    command:
      - '/bin/sh'
      - '-c'
      - |
        echo "$${SNMP_YAML}" > /etc/snmp_exporter/snmp.yaml
        exec /bin/snmp_exporter --config.file=/etc/snmp_exporter/snmp.yaml
    environment:
      SNMP_YAML: |
        # WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
        edgerouterx:
          walk:
          - 1.3.6.1.2.1.31.1.1.1.1
          - 1.3.6.1.2.1.31.1.1.1.10
          - 1.3.6.1.2.1.31.1.1.1.15
          - 1.3.6.1.2.1.31.1.1.1.6
          get:
          - 1.3.6.1.2.1.25.1.1.0
          - 1.3.6.1.4.1.2021.11.11.0
          - 1.3.6.1.4.1.2021.4.11.0
          - 1.3.6.1.4.1.2021.4.5.0
          metrics:
          - name: hrSystemUptime
            oid: 1.3.6.1.2.1.25.1.1
            type: gauge
            help: The amount of time since this host was last initialized - 1.3.6.1.2.1.25.1.1
          - name: ifHCOutOctets
            oid: 1.3.6.1.2.1.31.1.1.1.10
            type: counter
            help: The total number of octets transmitted out of the interface, including framing
              characters - 1.3.6.1.2.1.31.1.1.1.10
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ifHighSpeed
            oid: 1.3.6.1.2.1.31.1.1.1.15
            type: gauge
            help: An estimate of the interface's current bandwidth in units of 1,000,000 bits
              per second - 1.3.6.1.2.1.31.1.1.1.15
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ifHCInOctets
            oid: 1.3.6.1.2.1.31.1.1.1.6
            type: counter
            help: The total number of octets received on the interface, including framing
              characters - 1.3.6.1.2.1.31.1.1.1.6
            indexes:
            - labelname: ifIndex
              type: gauge
            lookups:
            - labels:
              - ifIndex
              labelname: ifName
              oid: 1.3.6.1.2.1.31.1.1.1.1
              type: DisplayString
          - name: ssCpuIdle
            oid: 1.3.6.1.4.1.2021.11.11
            type: gauge
            help: The percentage of processor time spent idle, calculated over the last minute
              - 1.3.6.1.4.1.2021.11.11
          - name: memTotalFree
            oid: 1.3.6.1.4.1.2021.4.11
            type: gauge
            help: The total amount of memory free or available for use on this host - 1.3.6.1.4.1.2021.4.11
          - name: memTotalReal
            oid: 1.3.6.1.4.1.2021.4.5
            type: gauge
            help: The total amount of real/physical memory installed on this host. - 1.3.6.1.4.1.2021.4.5
