version: "3"

networks:
  default:
    name: gateway_default

services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    hostname: home-assistant
    restart: always
    network_mode: host
    labels:
      - "traefik.http.routers.iot.rule=Host(`iot.zhaohai.li`)"
      - "traefik.http.routers.iot.entrypoints=https"
    volumes:
      - type: bind
        source: /share/System/config/home-assistant
        target: /config
    privileged: true
    expose:
      - "8123"
    # ports:
      # - 21063:21063
    environment:
      TZ: Europe/Berlin
