version: "3"

networks:
  default:
    name: gateway_default

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:0.12.1
    container_name: gotosocial
    hostname: gotosocial
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:8006
    labels:
      - "traefik.http.routers.gotosocial.rule=Host(`gts-w.zhaohai.li`)"
      - "traefik.http.routers.gotosocial.entrypoints=https"
    environment:
      GTS_HOST: gts-w.zhaohai.li
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      TZ: Europe/Berlin
    user: "0:0"
    expose:
      - "8080"
    volumes:
      - type: bind
        source: /share/System/config/gotosocial
        target: /gotosocial/storage

  nocodb:
    image: nocodb/nocodb:0.202.5
    container_name: nocodb
    hostname: nocodb
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:8006
    labels:
      - "traefik.http.routers.forms.rule=Host(`forms-w.zhaohai.li`)"
      - "traefik.http.routers.forms.entrypoints=https"
    volumes:
      - type: bind
        source: /share/System/config/nocodb
        target: /usr/app/data/
    expose:
      - "8080"
