version: "3"

networks:
  default:
    external:
      name: gateway_default

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    hostname: gotosocial
    labels:
      - "traefik.http.routers.gotosocial.rule=Host(`gts-w.zhaohai.li`)"
      - "traefik.http.routers.gotosocial.entrypoints=https"
    environment:
      GTS_HOST: gts-w.zhaohai.li
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
      TZ: Europe/Berlin
    user: "0:0"
    expose:
      - "8080"
    volumes:
      - /share/System/config/gotosocial:/gotosocial/storage
