---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-alloy
  namespace: infra
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: infra
spec:
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana-alloy
        namespace: infra
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: infra
  releaseName: alloy
  values:
    ingress:
      enabled: true
      annotations:
        # traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - collector-p.zhaohai.li
      faroPort: 12345
      tls:
      - hosts:
        - "*.zhaohai.li"
    crds:
      create: true
    rbac:
      create: true
    serviceAccount:
      create: true
    configReloader:
      enabled: true
    controller:
      type: 'daemonset'
      replicas: 1
    service:
      enabled: true
    serviceMonitor:
      enabled: false

    alloy:
      mounts:
        varlog: true
      configMap:
        create: true
        content: |
          logging {
            level  = "info"
            format = "logfmt"
          }

          prometheus.remote_write "default" {
            endpoint {
              url = "http://mimir.infra.svc:9009/api/v1/push"
            }
          }

          prometheus.remote_write "app" {
            endpoint {
              url = "http://mimir.infra.svc:9009/api/v1/push"
              headers = {
                "X-Scope-OrgID" = "app",
              }
            }
          }

          // discovery rules
          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.kubernetes "services" {
            role = "service"
          }

          discovery.kubernetes "endpoints" {
            role = "endpoints"
          }

          discovery.kubernetes "endpointslices" {
            role = "endpointslice"
          }

          discovery.kubernetes "ingresses" {
            role = "ingress"
          }

          discovery.kubernetes "nodes" {
            role = "node"
          }

          // infra monitor
          discovery.relabel "pod_scrape_infra" {
            targets = discovery.kubernetes.pods.targets

            rule {
              action = "drop"
              source_labels = ["__meta_kubernetes_namespace"]
              regex = "^default$"
            }

            rule {
              action = "keep"
              source_labels = ["__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape"]
              regex = "^true$"
            }

            rule {
              action = "replace"
              source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
              target_label = "__metrics_path__"
            }

            rule {
              action = "replace"
              source_labels = ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
              separator = ":"
              target_label = "__address__"
              regex = "^([0-9.]+)([:0-9]*):([0-9]+)$"
              replacement = "$1:$3"
            }
          }

          prometheus.scrape "infra" {
            scheme = "http"
            targets = discovery.relabel.pod_scrape_infra.output
            scrape_interval = "30s"
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // app monitor
          discovery.relabel "pod_scrape_app" {
            targets = discovery.kubernetes.pods.targets

            rule {
              action = "keep"
              source_labels = ["__meta_kubernetes_namespace"]
              regex = "^default$"
            }

            rule {
              action = "keep"
              source_labels = ["__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape"]
              regex = "^true$"
            }

            rule {
              action = "replace"
              source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
              target_label = "__metrics_path__"
            }

            rule {
              action = "replace"
              source_labels = ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
              separator = ":"
              target_label = "__address__"
              regex = "^([0-9.]+)([:0-9]*):([0-9]+)$"
              replacement = "$1:$3"
            }
          }

          prometheus.scrape "app" {
            scheme = "http"
            targets = discovery.relabel.pod_scrape_app.output
            scrape_interval = "30s"
            forward_to = [prometheus.remote_write.app.receiver]
          }

          // cadvisor
          discovery.relabel "cadvisor" {
            targets = discovery.kubernetes.nodes.targets

            rule {
              action = "replace"
              target_label = "__address__"
              replacement = "kubernetes.default.svc.cluster.local:443"
            }

            rule {
              source_labels = ["__meta_kubernetes_node_name"]
              regex = "(.+)"
              action = "replace"
              replacement = "/api/v1/nodes/${1}/proxy/metrics/cadvisor"
              target_label = "__metrics_path__"
            }

            rule {
              source_labels = ["__meta_kubernetes_node_name"]
              target_label  = "k8s_node_name"
            }
          }

          prometheus.scrape "cadvisor" {
            scheme = "https"
            tls_config {
                server_name = "kubernetes"
                ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                insecure_skip_verify = false
            }
            bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
            targets = discovery.relabel.cadvisor.output
            scrape_interval = "30s"
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // kubelet
          discovery.relabel "kubelet" {
            targets = discovery.kubernetes.nodes.targets

            rule {
              action = "replace"
              target_label = "__address__"
              replacement = "kubernetes.default.svc.cluster.local:443"
            }

            rule {
              source_labels = ["__meta_kubernetes_node_name"]
              regex = "(.+)"
              action = "replace"
              replacement = "/api/v1/nodes/${1}/proxy/metrics"
              target_label = "__metrics_path__"
            }

            rule {
              source_labels = ["__meta_kubernetes_node_name"]
              target_label  = "k8s_node_name"
            }
          }

          prometheus.scrape "kubelet" {
            scheme = "https"
            tls_config {
                server_name = "kubernetes"
                ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                insecure_skip_verify = false
            }
            bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
            targets = discovery.relabel.kubelet.output
            scrape_interval = "30s"
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // localhost
          prometheus.scrape "localhost" {
            targets = [
              {
                "__address__"   = "node-exporter.infra.svc:9110",
                "instance"      = "nas",
                "k8s_node_name" = "nas",
              },
            ]

            scrape_interval = "30s"
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // smartctl
          prometheus.scrape "smartctl" {
            targets = [
              {
                "__address__"   = "smartctl-exporter.infra.svc:80",
                "instance"      = "nas",
                "k8s_node_name" = "nas",
              },
            ]

            scrape_interval = "60s"
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // logging
          discovery.relabel "logs" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "k8s_namespace_name"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "k8s_node_name"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_kind"]
              target_label  = "k8s_controller_kind"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_name"]
              target_label  = "k8s_controller_name"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_kind", "__meta_kubernetes_pod_controller_name"]
              separator     = ";"
              regex         = "(.*);(.*)"
              target_label  = to_lower("k8s_${1}_name")
              replacement   = "${2}"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "k8s_pod_name"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "k8s_container_name"
            }

            rule {
              source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name", "__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
              separator     = ";"
              regex         = "(.*);(.*);(.*);(.*)"
              replacement   = "/var/log/pods/${1}_${2}_${3}/${4}/*.log"
              target_label  = "__path__"
            }
          }

          local.file_match "logs" {
            path_targets = discovery.relabel.logs.output
          }

          loki.source.file "pods" {
            targets    = local.file_match.logs.targets
            forward_to = [loki.process.logs.receiver]
          }

          loki.process "logs" {
            stage.cri {}
            forward_to = [loki.write.local.receiver]
          }

          loki.source.kubernetes_events "events" {
            log_format = "json"
            forward_to = [loki.write.local.receiver]
          }

          loki.write "local" {
            endpoint {
              url = "http://loki.infra.svc:3100/loki/api/v1/push"
            }
          }

