apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: infra
  releaseName: cert-manager
  values:
    installCRDs: true
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: 1.1.1.1:53
