apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-infra
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/config/infra"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
  namespace: infra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
