---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mimir"
  namespace: "infra"
data:
  runtime-config.yaml: |
    overrides:
      app:
        compactor_blocks_retention_period: 1y
  config.yaml: |
    multitenancy_enabled: true
    no_auth_tenant: "anonymous"

    limits:
      compactor_blocks_retention_period: "2w"

    server:
      http_listen_address: "0.0.0.0"
      http_listen_port: 9009
      log_level: "info"
      log_format: "json"

    activity_tracker:
      filepath: ""

    store_gateway:
      sharding_ring:
        replication_factor: 1

    blocks_storage:
      backend: "filesystem"
      bucket_store:
        sync_dir: "/mimir/tsdb-sync"
      filesystem:
        dir: "/mimir/data/tsdb"
      tsdb:
        dir: "/mimir/tsdb"

    memberlist:
      bind_addr: ["127.0.0.1"]

    compactor:
      data_dir: "/mimir/compactor"
      sharding_ring:
        kvstore:
          store: "memberlist"

    distributor:
      ring:
        instance_addr: "127.0.0.1"
        kvstore:
          store: "memberlist"

    ingester:
      ring:
        instance_addr: "127.0.0.1"
        kvstore:
          store: "memberlist"
        replication_factor: 1

    ruler_storage:
      backend: "filesystem"
      filesystem:
        dir: "/mimir/rules"

    ruler:
      rule_path: "/mimir/tmp/ruler"
---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mimir"
  namespace: "infra"
  labels:
    app: "mimir"
spec:
  replicas: 1
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: "mimir"
  template:
    metadata:
      labels:
        app: "mimir"
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: "mimir"
        image: "grafana/mimir:latest"
        imagePullPolicy: "Always"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        args:
        - "--config.file=/etc/mimir/config.yaml"
        - "--runtime-config.file=/etc/mimir/runtime-config.yaml"
        ports:
        - name: "http"
          containerPort: 9009
          protocol: "TCP"
        volumeMounts:
        - name: "storage"
          mountPath: "/mimir"
          subPath: "loki"
        - name: "config"
          mountPath: "/etc/mimir"
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: "/ready"
            port: "http"
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: "/ready"
            port: "http"
      volumes:
      - name: "storage"
        persistentVolumeClaim:
          claimName: "local-pvc"
      - name: "config"
        configMap:
          name: "mimir"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mimir"
  namespace: "infra"
spec:
  type: "ClusterIP"
  selector:
    app: "mimir"
  ports:
  - name: "http"
    port: 9009
    protocol: "TCP"
    targetPort: "http"

