---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "nanomq"
  namespace: "infra"
data:
  nanomq.conf: |
    http_server = {
      port = 8081               # HTTP server port
      ip_addr = "0.0.0.0"       # IP ADDR of HTTP server 
      limit_conn = 10           # Maximum number of outstanding requests NanoMQ can handle
      username = "admin"        # Username
      password = "public"       # Password
      max_body = 65535          # Max size of HTTP body server can accept
      auth_type = "basic"       # Authentication type, "basic" or "jwt"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanomq
  namespace: infra
  labels:
    app: nanomq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanomq
  template:
    metadata:
      labels:
        app: nanomq
    spec:
      volumes:
      - name: "config"
        configMap:
          name: "nanomq"
      containers:
      - name: nanomq
        image: emqx/nanomq:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - name: tcp
          containerPort: 1883
          protocol: TCP
        - name: ws
          containerPort: 8083
          protocol: TCP
        - name: ssl
          containerPort: 8883
          protocol: TCP
        - name: http
          containerPort: 8081
          protocol: TCP
        volumeMounts:
        - mountPath: "/etc/nanomq"
          name: "config"
        env:
        - name: NANOMQ_CONF_PATH
          value: "/etc/nanomq/nanomq.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: nanomq
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app: nanomq
  ports:
  - name: tcp
    port: 1883
    protocol: TCP
    targetPort: tcp
  - name: ws
    port: 8083
    protocol: TCP
    targetPort: ws
  - name: ssl
    port: 8883
    protocol: TCP
    targetPort: ssl
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
