apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 30m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-node-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: infra
  releaseName: node-exporter
  values:
    nameOverride: node-exporter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-infra
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: infra
  releaseName: prom-infra
  values:
    server:
      fullnameOverride: prom-infra
      retention: "7d"
      statefulSet:
        enabled: false
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        runAsGroup: 1001
        fsGroup: 1001
      persistentVolume:
        enabled: true
        existingClaim: config-claim
        subPath: "prom-infra"
      ingress:
        enabled: false
      extraFlags:
      - web.enable-lifecycle
      - web.enable-remote-write-receiver
    serverFiles:
      prometheus.yml:
        rule_files: []
        scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets:
                - localhost:9090

    rbac:
      create: false
    serviceAccounts:
      server:
        create: false
    alertmanager:
      enabled: false  
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false
