---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartctl-exporter
  namespace: infra
  labels:
    app.kubernetes.io/name: smartctl-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: smartctl-exporter
  namespace: infra
  labels:
    app.kubernetes.io/name: smartctl-exporter
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: smartctl-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smartctl-exporter
  namespace: infra
  labels:
    app.kubernetes.io/name: smartctl-exporter
spec:
  updateStrategy: 
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: smartctl-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smartctl-exporter
    spec:
      initContainers:
        - name: init
          image: "quay.io/prometheuscommunity/smartctl-exporter:latest"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - -c
            - |
              CMD=`update-smart-drivedb --dryrun --no-verify | sed 's/--max-redirect=0 //' | sed 's/-O [^ ]*/-O \/tmp\/drivedb.h/'`
              $CMD
              update-smart-drivedb --file /tmp/drivedb.h --no-verify
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: drivedb
              mountPath: /usr/share/smartmontools
      containers:
        - name: main
          image: "quay.io/prometheuscommunity/smartctl-exporter:latest"
          imagePullPolicy: Always
          args:
            - '--smartctl.path=/usr/sbin/smartctl'
            - '--smartctl.interval=120s'
            - '--web.listen-address=0.0.0.0:9633'
            - '--web.telemetry-path=/metrics'
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - name: http
              containerPort: 9633
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - name: dev
              mountPath: /hostdev
            - name: drivedb
              mountPath: /usr/share/smartmontools
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      serviceAccountName: smartctl-exporter
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: drivedb
          emptyDir: {}
      tolerations:
        - effect: NoSchedule
          operator: Exists
