---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "HelmRepository"
metadata:
  name: "bitnami"
  namespace: "infra"
spec:
  type: "oci"
  interval: "30m"
  url: "oci://registry-1.docker.io/bitnamicharts"
