# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: infra
#   labels:
#     kubernetes.io/metadata.name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    kubernetes.io/metadata.name: app
