deployment:
  enabled: true
  kind: Deployment
  replicas: 1
service:
  enabled: true
  single: true
  type: LoadBalancer
autoscaling:
  enabled: false
hostNetwork: false
rbac:
  enabled: true
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
podSecurityContext:
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

env:
- name: CF_API_EMAIL
  valueFrom:
    secretKeyRef:
      name: cloudflare-api-token-secret
      key: api-email
- name: CF_API_KEY
  valueFrom:
    secretKeyRef:
      name: cloudflare-api-token-secret
      key: api-token

global:
  checkNewVersion: false
  sendAnonymousUsage: false
logs:
  general:
    level: "INFO"  # @schema enum:[TRACE,DEBUG,INFO,WARN,ERROR,FATAL,PANIC]; default: "INFO"
    noColor: true
  access:
    enabled: true
metrics:
  prometheus:
    entryPoint: metrics

providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true
  kubernetesGateway:
    enabled: false
  file:
    enabled: false

ingressClass:
  enabled: true

gateway:
  enabled: false
  listeners:
    web:
      port: 80
      hostname: ""
      protocol: HTTP
      namespacePolicy:
    # websecure:
    #   port: 8443
    #   hostname:
    #   protocol: HTTPS
    #   namespacePolicy:
    #   certificateRefs:
    #   mode:

gatewayClass:
  enabled: false

ports:
  traefik:
    port: 8080
    expose:
      default: false
    exposedPort: 8080
    protocol: TCP
  metrics:
    port: 9100
    expose:
      default: false
    exposedPort: 9100
    protocol: TCP
  web:
    port: 1080
    expose:
      default: true
    exposedPort: 80
  websecure:
    port: 1443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
  wansecure:
    port: 8443
    expose:
      default: true
    exposedPort: 8443
    protocol: TCP
    tls:
      enabled: true

extraObjects:
- apiVersion: traefik.io/v1alpha1
  kind: Middleware
  metadata:
    name: wanauth
    namespace: infra-traefik
  spec:
    basicAuth:
      secret: wanauth
- apiVersion: traefik.io/v1alpha1
  kind: Middleware
  metadata:
    name: web-redirect
    namespace: infra-traefik
  spec:
    redirectScheme:
      scheme: https
      permanent: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [websecure]
    matchRule: Host(`gateway-p.zhaohai.li`)
    services:
    - name: api@internal
      kind: TraefikService
  web-redirect:
    enabled: true
    entryPoints: [web]
    matchRule: PathPrefix(`/`)
    middlewares:
    - name: "web-redirect"
    services:
    - name: traefik
      kind: Service
      port: web
  wanprivate:
    enabled: true
    entryPoints: ["wansecure"]
    matchRule: Host(`[a-z\-_.]+-p.zhaohai.li`)
    middlewares:
    - name: "wanauth"
    services:
    - name: traefik
      kind: Service
      port: websecure
  wanpublic:
    enabled: true
    entryPoints: [wansecure]
    matchRule: Host(`[a-z\-_.]*([^-][^p]|[^-].|.[^p]).zhaohai.li`)
    services:
    - name: traefik
      kind: Service
      port: websecure

# certificatesResolvers:
#   zhaohai.li:
#     acme:
#       email: me@zhaohai.li
#       caServer: https://acme-v02.api.letsencrypt.org/directory
#       storage: "/data/acme.json"       # Path to store the certificate information.
#       dnsChallenge:
#         provider: cloudflare
#         resolvers: ["1.1.1.1"]
