apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitor
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: loki
          image: grafana/loki:3.2.2
          imagePullPolicy: IfNotPresent
          args:
            - "--compactor.compaction-interval=10m"
            - "--config.file=/etc/loki/local-config.yaml"
            - "--store.retention=7d"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          volumeMounts:
            - mountPath: /loki
              name: data
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
      volumes:
        - name: data
          hostPath:
            path: /mnt/data/config/loki
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitor
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      protocol: TCP
      targetPort: http
