apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitor
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.7.0
        imagePullPolicy: IfNotPresent
        args:
        - '--path.rootfs=/hostfs'
        ports:
        - containerPort: 9100
          hostPort: 9100
          protocol: TCP
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
      hostNetwork: true
      volumes:
      - name: hostfs
        hostPath:
          path: /
