apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitor
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 1m
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitor
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: prometheus
          image: prom/prometheus:v2.51.0
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --enable-feature=otlp-write-receiver
            - --web.enable-remote-write-receiver
            - --web.listen-address=0.0.0.0:9090
            - --web.external-url=http://prometheus.monitor.svc.cluster.local:9090/
            - --storage.tsdb.path=/prometheus/data
            - --storage.tsdb.retention.time=7d
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /prometheus/data
              name: data
            - mountPath: /etc/prometheus
              name: config
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
      volumes:
        - name: data
          hostPath:
            path: /mnt/data/config/prometheus
        - name: config
          configMap:
            defaultMode: 0444
            name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitor
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: http
