- name: set variables
  set_fact:
    mount_src: //nas/Multimedia
    mount_point: /mnt/multimedia
    cred_path: /etc/smbcred

- name: install cifs package
  package:
    name: cifs-utils
    state: present
  become: yes

- name: create cifs credentials
  copy:
    dest: "{{ cred_path }}"
    mode: 0600
    owner: root
    group: root
    content: |
      username=googol
      password=V2R6u8Kc
  become: yes

- name: create mount point
  file:
    path: "{{ mount_point }}"
    owner: googol
    group: googol
    mode: 0755
    state: directory
  become: yes

- name: mount multimedia directory
  mount:
    path: "{{ mount_point }}"
    src: "{{ mount_src }}"
    fstype: cifs
    opts: "vers=3,credentials={{ cred_path }},iocharset=utf8,uid=googol,gid=googol,rw"
    state: mounted
  become: yes
