apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-zhaohai-li-dns
spec:
  acme:
    email: me@zhaohai.li
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: zhaohai-li-home-cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
