apiVersion: v1
kind: ConfigMap
metadata:
  name: w2l-proxy
  namespace: export
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /dev/stderr;
    events {
      worker_connections  1024;
    }
    http {
      access_log /dev/stdout;

      server {
        listen       80;
        server_name  _ default;
        location / {
          # Required to proxy the connection to Cockpit
          proxy_pass https://zhaohai.li;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;

          # Required for web sockets to function
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          gzip off;
          proxy_ssl_verify off;
        }
      }

      server {
        listen       80;
        server_name  ~^(.+)-p.zhaohai.li$;
        auth_basic "Administrator’s Area";
        auth_basic_user_file /etc/auth/users;
        location / {
          # Required to proxy the connection to Cockpit
          proxy_pass https://zhaohai.li;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;

          # Required for web sockets to function
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          gzip off;
          proxy_ssl_verify off;
        }
      }
    }
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: wanauth
  namespace: export
spec:
  basicAuth:
    secret: wanauth
---
apiVersion: v1
kind: Service
metadata:
  name: w2l-proxy
  namespace: export
spec:
  type: ClusterIP
  selector:
    app: w2l-proxy
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: w2l-proxy
  namespace: export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w2l-proxy
  template:
    metadata:
      labels:
        app: w2l-proxy
    spec:
      containers:
      - name: w2l-proxy
        image: nginx:1.25
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx
          readOnly: true
        - name: wanauth
          mountPath: /etc/auth
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: w2l-proxy
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: wanauth
        secret:
          secretName: wanauth
          items:
          - key: users
            path: users
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: w2l-proxy
  namespace: export
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: wansecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - "zhaohai.li"
    - "*.zhaohai.li"
    secretName: tls-zhaohai-li-ingress-dns
  rules:
  - host: '*.zhaohai.li'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: w2l-proxy
            port:
              number: 80
