apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  name: "services"
  namespace: "flux-system"
spec:
  dependsOn:
  - name: "infra"
  interval: "1h0m0s"
  path: "./home-cluster/services"
  prune: true
  retryInterval: "2m0s"
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
  targetNamespace: "default"
  timeout: "15m0s"
  wait: true
