apiVersion: v1
kind: ConfigMap
metadata:
  name: cockpit-proxy
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /dev/stderr;
    events {
      worker_connections  1024;
    }
    http {
      access_log /dev/stdout;
      server {
        listen       80;
        server_name  _;
        location / {
          # Required to proxy the connection to Cockpit
          proxy_pass https://nas.local:9090;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;

          # Required for web sockets to function
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          # Pass ETag header from Cockpit to clients.
          # See: https://github.com/cockpit-project/cockpit/issues/5239
          gzip off;
          proxy_ssl_verify off;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: cockpit-proxy
spec:
  type: ClusterIP
  selector:
    app: cockpit-proxy
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockpit-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockpit-proxy
  template:
    metadata:
      labels:
        app: cockpit-proxy
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: cockpit-proxy
        image: nginx:1.25
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: conf
      volumes:
      - name: conf
        configMap:
          name: cockpit-proxy
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cockpit-proxy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - "*.zhaohai.li"
    secretName: tls-zhaohai-li-ingress-dns
  rules:
  - host: nas.zhaohai.li
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cockpit-proxy
            port:
              number: 80
