apiVersion: v1
kind: Pod
metadata:
  name: media
  labels:
    app: media
spec:
  containers:
  - name: media
    image: jellyfin/jellyfin:10.8.13-1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8096
      protocol: TCP
    volumeMounts:
    - mountPath: /dev/dri
      name: dev-dri
    - mountPath: /media
      name: media
    - mountPath: /config
      name: config
    - mountPath: /cache
      name: cache
    securityContext:
      privileged: true
    env:
    - name: "JELLYFIN_PublishedServerUrl"
      value: "https://media.zhaohai.li"
    resources:
      limits:
        cpu: 1.5
        memory: 2Gi
      requests:
        cpu: 0.7
        memory: 512Mi
  volumes:
  - name: dev-dri
    hostPath:
      path: /dev/dri
  - name: media
    hostPath:
      path: /mnt/data/media
  - name: config
    hostPath:
      path: /mnt/data/config/jellyfin/config
  - name: cache
    hostPath:
      path: /mnt/data/config/jellyfin/cache
---
apiVersion: v1
kind: Service
metadata:
  name: media
spec:
  type: ClusterIP
  selector:
    app: media
  ports:
    - name: http
      port: 8096
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media
  annotations:
   cert-manager.io/issuer: "cert-zhaohai-li-dns"
spec:
  tls:
  - hosts:
    - "media.zhaohai.li"
    secretName: tls-media-ingress-dns
  rules:
  - host: "media.zhaohai.li"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: media
            port:
              number: 8096
