apiVersion: apps/v1
kind: Deployment
metadata:
  name: bt
  labels:
    app: bt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bt
  template:
    metadata:
      labels:
        app: bt
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: bt
        image: linuxserver/qbittorrent:4.6.7
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /media
          name: media
        - mountPath: /config
          name: config
        env:
        - name: "WEBUI_PORT"
          value: "8080"
        - name: "TZ"
          value: "Europe/Berlin"
        - name: "PUID"
          value: "1000"
        - name: "PGID"
          value: "1000"
      volumes:
      - name: media
        hostPath:
          path: /mnt/data/media
      - name: config
        hostPath:
          path: /mnt/data/config/qbittorrent
---
apiVersion: v1
kind: Service
metadata:
  name: bt
spec:
  type: ClusterIP
  selector:
    app: bt
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bt
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "cert-zhaohai-li-dns"
spec:
  tls:
  - hosts:
    - "*.zhaohai.li"
    secretName: tls-zhaohai-li-ingress-dns
  rules:
  - host: "bt.zhaohai.li"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bt
            port:
              number: 8080
