---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "cert-manager"
  namespace: "infra"
spec:
  interval: "1h"
  chart:
    spec:
      chart: "cert-manager"
      sourceRef:
        kind: "HelmRepository"
        name: "jetstack"
        namespace: "infra"
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
    installCRDs: false
