---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "cert-manager"
  namespace: "infra"
spec:
  interval: "1h"
  chart:
    spec:
      chart: "cert-manager"
      sourceRef:
        kind: "HelmRepository"
        name: "jetstack"
        namespace: "infra"
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
    installCRDs: false
    extraArgs:
    - "--dns01-recursive-nameservers-only"
    - "--dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53"
---
apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "cloudflare"
spec:
  acme:
    email: "me@zhaohai.li"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: "letsencrypt-account-key"
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: "cloudflare-api-token-secret"
            dns-api-token: "api-token"
