# ---
# apiVersion: "gateway.networking.k8s.io/v1"
# kind: "Gateway"
# metadata:
#   name: "entrypoints"
#   namespace: "infra"
# spec:
#   gatewayClassName: "traefik"
#   listeners:
#   - name: "https-lan"
#     protocol: "HTTPS"
#     port: 443
#     tls:
#       mode: "Terminate"
#       certificateRefs: [{ name: "lan-tls-secret" }]
#     allowedRoutes:
#       namespaces: { from: "All" }
---
apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "lan-gateway-cert"
  namespace: "infra"
spec:
  secretName: "lan-tls-secret"
  issuerRef:
    name: "cloudflare"
    kind: "ClusterIssuer"
  dnsNames:
  - "*.zhaohai.li"
  - "zhaohai.li"
  privateKey:
    algorithm: "ECDSA"
    size: 512
