---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "Gateway"
metadata:
  name: "entrypoint"
  namespace: "infra"
spec:
  gatewayClassName: "traefik"
  listeners:
  - name: "https-lan"
    protocol: "HTTPS"
    port: 9443
    tls:
      mode: "Terminate"
      certificateRefs: [{ name: "lan-tls-secret" }]
    allowedRoutes:
      namespaces: { from: "All" }
