---
apiVersion: v1
kind: Pod
metadata:
  name: samba
  namespace: infra
  labels:
    app: samba
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  containers:
    - name: samba
      image: alpine:latest
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          drop:
            - ALL
          add:
            - CHOWN
            - DAC_OVERRIDE
            - SETUID
            - SETGID
            - SYS_CHROOT
            - NET_BIND_SERVICE
      env:
        - name: SMB_USER
          valueFrom:
            secretKeyRef: { name: smb-auth, key: SMB_USER }
        - name: SMB_UID
          valueFrom:
            secretKeyRef: { name: smb-auth, key: SMB_UID }
        - name: SMB_GROUP
          valueFrom:
            secretKeyRef: { name: smb-auth, key: SMB_GROUP }
        - name: SMB_GID
          valueFrom:
            secretKeyRef: { name: smb-auth, key: SMB_GID }
        - name: SMB_PASS
          valueFrom:
            secretKeyRef: { name: smb-auth, key: SMB_PASS }
      command: ["/bin/sh", "-c"]
      args:
        - |
          apk add --no-cache samba shadow su-exec

          groupadd -g ${SMB_GID} ${SMB_GROUP}
          useradd -u ${SMB_UID} -g ${SMB_GROUP} -s /sbin/nologin -M ${SMB_USER}

          rm -rf /etc/samba/*
          sed "s/__SMB_GROUP__/${SMB_GROUP}/g" /etc/samba/templates/smb.conf.template > /etc/samba/smb.conf
          echo -e "${SMB_PASS}\n${SMB_PASS}" | smbpasswd -a -s ${SMB_USER}

          exec su-exec ${SMB_USER}:${SMB_GROUP} smbd -F --no-process-group </dev/null
      volumeMounts:
        - name: config
          mountPath: /etc/samba/templates/smb.conf.template
          subPath: smb.conf.template
        - name: host-storage
          mountPath: /mnt/data/media
      ports:
        - containerPort: 445
          hostPort: 445
          name: smb-port
    - name: avahi
      image: alpine:latest
      imagePullPolicy: Always
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
          add:
            - NET_ADMIN
            - NET_BIND_SERVICE
      command: ["/bin/sh", "-c"]
      args:
        - |
          apk add --no-cache avahi
          exec avahi-daemon -F
      volumeMounts:
        - name: config
          mountPath: /etc/avahi/avahi-daemon.conf
          subPath: avahi-daemon.conf
        - name: config
          mountPath: /etc/avahi/services/smb.service
          subPath: avahi.smb.service
      ports:
        - containerPort: 5353
          hostPort: 5353
          protocol: UDP
          name: mdns-port
  volumes:
    - name: config
      configMap:
        name: samba-configs
    - name: host-storage
      hostPath:
        path: /mnt/data/media
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
  namespace: infra
data:
  smb.conf.template: |
    [global]
      min protocol = SMB2
      workgroup = WORKGROUP
      server string = nas samba server
      server role = standalone server
      logging = stdout
      log level = 1
      guest account = nobody
      
      aio read size = 16384
      aio write size = 16384
      use sendfile = yes

    [media]
      comment = My Media
      path = /mnt/data/media
      writeable = yes
      browseable = yes
      guest ok = no
      public = no
      create mask = 0644
      directory mask = 0755
      valid users = @__SMB_GROUP__
  avahi-daemon.conf: |
    [server]
    enable-dbus=no
    use-ipv4=yes
    use-ipv6=no
    ratelimit-interval-usec=1000000
    ratelimit-burst=1000

    [wide-area]
    enable-wide-area=yes

    [publish]
    publish-addresses=yes
    publish-hinfo=no
    publish-workstation=no
    publish-domain=no

    [refuse-options]
  avahi.smb.service: |
    <?xml version="1.0" standalone='no'?>
    <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
    <service-group>
      <name replace-wildcards="yes">%h</name>
      <service>
        <type>_smb._tcp</type>
        <port>445</port>
      </service>
      <service>
        <type>_device-info._tcp</type>
        <port>0</port>
        <txt-record>model=Macmini</txt-record>
      </service>
    </service-group>
